# Generated by Django 5.2.8 on 2025-11-14 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_question_submission_answer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Entry',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
