# Generated by Django 5.2.8 on 2025-11-18 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_delete_entry_delete_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='nickname',
        ),
        migrations.AddField(
            model_name='submission',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
