# Generated by Django 5.2.8 on 2025-11-19 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_remove_submission_nickname_submission_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
