# Generated by Django 5.2.8 on 2025-11-21 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_question_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='choices',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='question',
            name='input_type',
            field=models.CharField(choices=[('text', 'Text'), ('radio', 'Radio')], default='text', max_length=10),
        ),
    ]
